### ISSUE TITLE
Other language

### ISSUE THREAD

**Issue by Calamus-Cajan** [Froussios/Intro-To-RxJava#23]
Other language interpreter?

**Comment by Froussios** [comment]
If you are willing to translate this, you may do so. Remember to follow the MIT license. Also appreciated if you remember to give credit to the originals: this and 
www.introtorx.com.

I have seen translations to Russian and Chinese, but I cannot endorse them, since I don't speak those languages and I have no idea if they are good.

**Comment by Calamus-Cajan** [comment]
Thank you very much, I found a Chinese translation. Whatever the language, as long as Rxjava understand the true meaning.
